CREATE ROLE bitevents_app WITH
    LOGIN
    PASSWORD '${APP_DB_PASSWORD}'
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOBYPASSRLS
    NOTEMPORARY
    CONNECTION LIMIT 50;

GRANT CONNECT ON DATABASE bitevents_db TO bitevents_app;

GRANT USAGE ON SCHEMA public TO bitevents_app;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO bitevents_app;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO bitevents_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE ON TABLES TO bitevents_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE ON SEQUENCES TO bitevents_app;

REVOKE CREATE ON SCHEMA public FROM bitevents_app;